 /* PROJECT
  passenger name , driver name , location, ola cab id , vehicle number plate,
  time arrival, deoarture time with location, cost ,  
  reserved, booked, occuped, cash/online 
  */



CREATE DATABASE MON;
USE MON;
CREATE TABLE PASSENGER
(
 PASS_ID INT PRIMARY KEY,
 PASS_NAME VARCHAR(45),
 PASS_MOBILE BIGINT,
 COST_MODE ENUM("ONLINE","CASH"),
 ARRIVAL VARCHAR(35),
 DEPARTURE VARCHAR(35)
);

-- table  show 
SELECT * FROM PASSENGER;

CREATE TABLE OLA
(
 OLA_CAB_ID INT PRIMARY KEY,
 CAB_NAME VARCHAR(45),
 LOCATION VARCHAR(45),
 VEHICLE_NUMBER VARCHAR(45),
 COST INT,
 CAB_DRIVER ENUM("RESERVED","AVAILABLE"),
 DATEE DATETIME,
 OLA_PASSENGER INT, 
FOREIGN KEY(OLA_PASSENGER) REFERENCES PASSENGER(PASS_ID)
);

SELECT * FROM OLA;


-- here inner join method use

SELECT * FROM PASSENGER 
 JOIN OLA
ON PASSENGER.PASS_ID = OLA.OLA_PASSENGER;

-- here left join method use

SELECT * FROM PASSENGER 
LEFT JOIN OLA
ON PASSENGER.PASS_ID = OLA.OLA_PASSENGER;

-- here right method use

SELECT * FROM PASSENGER 
RIGHT JOIN OLA
ON PASSENGER.PASS_ID = OLA.OLA_PASSENGER;